# Site settings
title: danlucas
email: dan.lucas@gmail.com
description: "A danlucas blog... this is a lot of danlucas in one spot..."
baseurl: ""
url: "http://danlucas.github.io"
twitter_username: danlucas
github_username:  danlucas

# Build settings
markdown: kramdown
permalink: pretty
