# Site settings
title: danlucas
email: dan.lucas@gmail.com
description: "A danlucas blog... this is a lot of danlucas in one spot..."
baseurl: ""
url: "http://danlucas.github.io"
twitter_username: danlucas
github_username:  danlucas

# Build settings
markdown: kramdown
permalink: pretty
exclude: [Rakefile]

# Rake config
post:
    template: _layouts/post.html
    extension: md
page:
    template: page.html
    extension: md
git:
    branch: master
editor: subl

# collections
collections:
    practice:
        output: true
        title: "Practice"
    mocks:
        output: true
